services:
  - type: web
    name: mashup-generator-102303599
    env: python
    plan: free
    buildCommand: |
      apt-get update
      apt-get install -y ffmpeg
      pip install -r requirements.txt
    startCommand: gunicorn webapp.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11

